* <2022-06-15 Wed> Ideas para el c贸digo
 
** vital
 Integrar los generadores de vecindad (neigh-suite) con el grafo de evaluacion.

*** definir el orden del lectura
*** fijate del vrp-suite.org
*** definir una nueva solucion (que puede ser la que ya existe)
*** reescribir la evaluacion automatica
   - 茅l uso gagm para crear las clases :-(
   - defclass def-vrp-class (s谩calo del vrp-suite)
   - definir una soluci贸n nueva
   - adaptar lo que existe a esa soluci贸n (limpiar c贸digo)

*** neigh-suite esta *casi* bien.
   - usar la misma clase soluci贸n que hagas t煤
   - y las mismas operaciones que modifican la soluci贸n
     - seleccionar cliente *coordenadas*
     - insertar cliente *coordenadas*
   - eliminar un poco de c贸digo repetido
     - herencia
     - macros
*** heidy 
   
* <2022-04-23 Sat> Planilla de inscripcion de tesis
** titulo
Implementacion de un sistema para la solucion agil de problemas de enrutamiento de vehiculos
** objetivos generales
El objetivo de este proyecto es implementar un sistema que permita resolver un problema de enrutamiento de vehiculos con el menor esfuerzo humano posible.  

   Para ello es necesario (objetivos especificos):

   - estudiar las tesis anteriores que abordan este problema
   - estudiar el codigo de las tesis anteriores
   - disear un sistema que permita combinarlas de manera organica
   - implementar la propuesta realizada
   - analizar los resultados que se obtienen al usarla

** resumen tecnico
Durante aos, en nuestra facultad se han desarrollado varios trabajos que permiten agilizar la soluci贸n de un problema de enrutamiento de veh铆culos.  En este contexto, agilizar la soluci贸n significa que haya que dedicarle poco esfuerzo humano.  Cada uno de estos trabajos ha abordado una arista diferente de la automatizaci贸n de la soluci贸n del problema de enrutamiento de veh铆culos.

Con esta tesis se propone dise帽ar e implementar un sistema que permite unir cada uno de esos trabajos previos para comenzar a resolver problemas de enrutamiento de veh铆culos en poco tiempo.

** cronograma
- Enero -- Abril 2022: 

 Estudio de los trabajos anteriores para la soluci贸n autom谩tica de un VRP

- Abril -- Mayo 2022: 

 Estudio y modificaci贸n del c贸digo las propuestas anteriores.

- Mayo -- Julio 2022:

 Dise帽o e implementaci贸n de la propuesta para la soluci贸n 谩gil de problemas de VRP

- Agosto - Octubre:

 Puesta a punto del sistema, experimentaci贸n y escritura del documento

- Noviembre 2022: 

 Escritura del documento y entrega

